name: web-youtube-dl CI
on:
  push:

jobs:
  ci:
    name: Run full testing pipeline
    runs-on: ubuntu-latest

    # Missing ffmpeg
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set target python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - name: Install poetry
        run: python -m pip install poetry


      - name: Install the project and dependencies
        run: |
          apt install ffmpeg
          poetry install

      - name: Run tests
        run: make test